# Generated by Django 2.2 on 2019-05-09 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_analyzer.SavedPage')),
            ],
        ),
        migrations.CreateModel(
            name='IgnoredKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_analyzer.SavedPage')),
            ],
        ),
        migrations.CreateModel(
            name='ContentUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_analyzer.SavedPage')),
            ],
        ),
    ]
