# Generated by Django 2.2 on 2019-06-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('default', models.BooleanField()),
                ('groups_have_access', models.ManyToManyField(blank=True, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='SavedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_analyzer.Project')),
            ],
        ),
        migrations.CreateModel(
            name='TargetKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_analyzer.SavedPage')),
            ],
        ),
        migrations.CreateModel(
            name='IgnoredKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_analyzer.SavedPage')),
            ],
        ),
        migrations.CreateModel(
            name='ContentUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_analyzer.SavedPage')),
            ],
        ),
    ]
